name: Test DDEV addon
on:
  workflow_call:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false
      os:
        type: string
        description: Operating system to test
        required: false
        default: '["ubuntu-latest", "macos"]'
      ddev_version:
        type: string
        description: DDEV version to test
        required: false
        default: '["stable"]'
      test_type:
        type: string
        description: Test type to run. Can be "local" or "release"
        required: false
        default: "release"

jobs:
  run_ddev_tests:
    name: Test ${{ matrix.ddev_version }} on ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.os)}}
        ddev_version: ${{ fromJSON(inputs.ddev_version)}}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Test the addon
        uses: oblakstudio/action-test-ddev-addon@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          test_type: ${{ inputs.test_type }}
          ddev_version: ${{ matrix.ddev_version }}
          debug_enabled: ${{ inputs.debug_enabled }}
